### ISSUE TITLE
plugin is broken from update 

### ISSUE THREAD

**Issue by wolfhound871** [cartman-2000/Rocket-Plugin-Wrecking-Ball#11]
https://i.imgur.com/oyTrHDq.png

**Comment by cartman-2000** [comment]
I've uploaded a recompiled version of the plugin.
https://github.com/cartman-2000/Rocket-Plugin-Wrecking-Ball/releases/latest

**Comment by wolfhound871** [comment]
seems to be ok ....... unless you know why this is [Error] Could not find dependency: I18N, Version=4.0.0.0,

**Comment by wolfhound871** [comment]
fixed thanks cartman

**Comment by cartman-2000** [comment]
The bit about I18N is probably from something else, plugins that use MySQL can use that, mine doesn't, but other's like Uconomy do. The update to 3.29.1.0 updated the base .net target for the game to .net 4.0, which could negatively effect old plugins that were compiled against .net 3.5 and below.

**Comment by wolfhound871** [comment]
i figured that out even though getting the right files to fix that was super hard i pulled that statement after i figured it out guess you could still see it thanks for the reply though and your work it helps my community staff every day 
        
               [ owner wolfhound of carbonfibergaming ]
