### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by BraianKant** [cartman-2000/Rocket-Plugin-Wrecking-Ball#12]
When i using the "/wreck confirm" command, it drops all cleaned items on the ground.
![image](https://user-images.githubusercontent.com/41028671/53296233-eac4e700-382c-11e9-857f-713dc4abca1c.png)
![image](https://user-images.githubusercontent.com/41028671/53296236-f0223180-382c-11e9-92ca-186a728d2589.png)

**Comment by cartman-2000** [comment]
Not a bug, it's a feature that I added to the mod a week or two ago. It can be disabled by setting EnableVehicleElementDrop and EnableDestroyedElementDrop to false.

**Comment by BraianKant** [comment]
Thanks =)
