### ISSUE TITLE
Feature Request: Use shorter timer and duty cycle cap.

### ISSUE THREAD

**Issue by Ruedii** [cartman-2000/Rocket-Plugin-Wrecking-Ball#3]
Using a 20ms timer (50 times a second) with fewer objects per a cycle would drastically reduce lag generated.

Furthermore, if you put the cap as a timer from when the script is launched (e.g. spend 5ms on cleanup) it would allow the system to scale.

It should also automatically skip cycles if TPS is not being met for all players.

**Comment by cartman-2000** [comment]
You can change the rates with the current config options in the plugin, like you could have it run just about every server frame by setting the DestructionRate to 60 or higher, and the DestructionsPerInterval to 1 to 2, that would destroy "up to" 60 to 120 items per second. The actual rate of that would be variable on the server side tps, like if you were getting 10 tps, you'd only get 20 destructions per second with a DestructionsPerInterval  of 2.  It wouldn't make much of a difference for client side lag though, but server side lag would be minimal for either. 

The destruction timers are tied to server frames, so you can only have up to 60 runs per second, as the server tps is locked at 60 tps. The destruction loop is buggy if it's ran out of the main server thread, and the destructions would need to be locked to the main thread anyways for it not to corrupt the structure/elements lists on the server(which would force you to restart the server.).

The default settings does ~10 runs per second and 10 elements per run, which is 100 elements per second, at the top destruction speed.
