### ISSUE TITLE
last unturned update broke the plugin 

### ISSUE THREAD

**Issue by wolfhound871** [cartman-2000/Rocket-Plugin-Wrecking-Ball#4]
AFTER THE LAST UPDATE FROM UNTURNED THE PLUGIN IS BROKEN I HAVE THE LATEST VERSION OF WRECKING BALL INSTALLED    error says [6/10/2018 3:22:16 PM] [Error] MissingMethodException: Method not found: 'SDG.Unturned.StructureManager.damage'. - ApokPT.RocketPlugins.WreckingBall.Update ()   when i try using it that spams the console

**Comment by joeytheadmingamer** [comment]
I have the same error, please find a resolution.

**Comment by DronXa** [comment]
Same error ;/

**Comment by cartman-2000** [comment]
I rebuilt the plugin on the plugin page, but the unturned refs that are used on the rocket plugin compiling server's tend to be out of date for a while after an update to unturned. you can try this url instead, if the one on the plugin page doesn't work.

(rebuilt against the latest UT libs)
https://github.com/cartman-2000/Rocket-Plugin-Wrecking-Ball/releases/tag/3.6.2.1

**Comment by wolfhound871** [comment]
the above link fixed it it works again thanks cartman-2000 amazing work and response

**Comment by thereis** [comment]
Broke again

**Comment by NoAdO** [comment]
Doesn't work in last update (plugin from the link above).

Server's log:
`[World] Лучезарный [NoAdO]: "/wreck * 20"
WreckingBall >> Player Лучезарный [NoAdO] (76561198119961715), queued wreck at: (-56.8, 59.8, 214.9), with Flag type: Normal, with Flags: *, with itemID: 0, with StermID: 0, number of elements queued: 16
[World] Лучезарный [NoAdO]: "/wreck confirm"
WreckingBall >> Player Лучезарный [NoAdO] (76561198119961715) has initiated wreck.
MissingMethodException: Method not found: 'SDG.Unturned.StructureManager.damage'. - ApokPT.RocketPlugins.WreckingBall.Update ()
MissingMethodException: Method not found: 'SDG.Unturned.StructureManager.damage'. - ApokPT.RocketPlugins.WreckingBall.Update ()`

**Comment by cartman-2000** [comment]
Try this one.

**Comment by NoAdO** [comment]
No need. I've reinstalled the plugin and it fixed (3.6.2.1). Thanks for your work.
