### ISSUE TITLE
/wreck confirm ERROR

### ISSUE THREAD

**Issue by DiBaDu** [cartman-2000/Rocket-Plugin-Wrecking-Ball#5]
Im Using unturned 3.26.0.2

I can search placed items with /wreck 1098 6  but if i want to remove with /wreck confirm  nothing is happened. Just long errors in log

**Comment by cartman-2000** [comment]
Have you tried to run the plugin from the release section of this git repo? If you're trying to use the one that was compiled on the rocket plugins site, it may not work, as the libs that build server uses are usually a bit out of date. That build serveraalso verrides my libs in the repo so I can't get a working version there, if I need to recompile the plugin against newer libs.

https://github.com/cartman-2000/Rocket-Plugin-Wrecking-Ball/releases/tag/3.6.2.2
