### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by BraianKant** [cartman-2000/Rocket-Plugin-Wrecking-Ball#7]
MissingMethodException: Method not found: 'SDG.Unturned.Animal.askDamage'. - ApokPT.RocketPlugins.WreckingBall.Update ()

**Comment by cartman-2000** [comment]
Have you tried this build?
https://github.com/cartman-2000/Rocket-Plugin-Wrecking-Ball/releases/tag/3.6.2.3
I'm keeping the builds on the git pages more upto date than the ones off of the rocket plugin page, as the libs on the rocket plugin build servers are out of date most of the time.
